In [11]:
import pandas as pd

In [14]:
personasf_df = pd.read_csv('persona_fisica.csv')
personasf_df.head()

,anio_inicio,mes_inicio,fecha_inicio,hora_inicio,anio_hecho,mes_hecho,fecha_hecho,hora_hecho,delito,categoria_delito,...,tipo_persona,calidad_juridica,competencia,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho,latitud,longitud
0,2024,Enero,2024-01-01,13:53:00,2023.0,Julio,2023-07-22,12:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FISICA,DENUNCIANTE Y VICTIMA,FUERO COMUN,REFORMA SOCIAL,Reforma Social,MIGUEL HIDALGO,Miguel Hidalgo,CDMX,19.435099,-99.212288
1,2024,Enero,2024-01-01,14:50:00,2023.0,Diciembre,2023-12-30,12:20:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FISICA,DENUNCIANTE Y VICTIMA,FUERO COMUN,JUÁREZ,Juarez,CUAUHTEMOC,Cuauhtémoc,CDMX,19.426143,-99.161645
2,2024,Enero,2024-01-01,22:09:00,2023.0,Diciembre,2023-12-29,01:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FISICA,DENUNCIANTE Y VICTIMA,FUERO COMUN,ANZURES,Anzures,MIGUEL HIDALGO,Miguel Hidalgo,CDMX,19.435483,-99.182680
3,2024,Enero,2024-01-02,12:05:00,2023.0,Octubre,2023-10-21,12:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FISICA,DENUNCIANTE Y VICTIMA,FUERO COMUN,RESIDENCIAL MIRAMONTES,Residencial Miramontes,TLALPAN,Tlalpan,CDMX,19.302997,-99.122575
4,2024,Enero,2024-01-02,12:11:00,2023.0,Diciembre,2023-12-27,02:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FISICA,DENUNCIANTE Y VICTIMA,FUERO COMUN,SAN JERÓNIMO MIACATLÁN,Pueblo San Jeronimo Miacatlan,MILPA ALTA,Milpa Alta,CDMX,19.190244,-99.005512

In [ ]:
personasf_df['fecha_inicio'] = pd.to_datetime(personasf_df['fecha_inicio'])
personasf_df['anio_inicio'] = personasf_df['fecha_inicio'].dt.year
personasf_df['mes_inicio'] = personasf_df['fecha_inicio'].dt.month
personasf_df['dia_inicio'] = personasf_df['fecha_inicio'].dt.day

personasf_df['fecha_hecho'] = pd.to_datetime(personasf_df['fecha_hecho'])
personasf_df['anio_hecho'] = personasf_df['fecha_hecho'].dt.year
personasf_df['mes_hecho'] = personasf_df['fecha_hecho'].dt.month
personasf_df['dia_hecho'] = personasf_df['fecha_hecho'].dt.day

personasf_df

,anio_inicio,mes_inicio,fecha_inicio,hora_inicio,anio_hecho,mes_hecho,fecha_hecho,hora_hecho,delito,categoria_delito,...,competencia,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho,latitud,longitud,dia_inicio,dia_hecho
0,2024,1,2024-01-01,13:53:00,2023,7,2023-07-22,12:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,REFORMA SOCIAL,Reforma Social,MIGUEL HIDALGO,Miguel Hidalgo,CDMX,19.435099,-99.212288,1,22
1,2024,1,2024-01-01,14:50:00,2023,12,2023-12-30,12:20:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,JUÁREZ,Juarez,CUAUHTEMOC,Cuauhtémoc,CDMX,19.426143,-99.161645,1,30
2,2024,1,2024-01-01,22:09:00,2023,12,2023-12-29,01:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,ANZURES,Anzures,MIGUEL HIDALGO,Miguel Hidalgo,CDMX,19.435483,-99.182680,1,29
3,2024,1,2024-01-02,12:05:00,2023,10,2023-10-21,12:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,RESIDENCIAL MIRAMONTES,Residencial Miramontes,TLALPAN,Tlalpan,CDMX,19.302997,-99.122575,2,21
4,2024,1,2024-01-02,12:11:00,2023,12,2023-12-27,02:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,SAN JERÓNIMO MIACATLÁN,Pueblo San Jeronimo Miacatlan,MILPA ALTA,Milpa Alta,CDMX,19.190244,-99.005512,2,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4385,2024,7,2024-07-31,22:18:57,2024,7,2024-07-29,11:30:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,SANTA CRUZ ATOYAC,Santa Cruz Atoyac,BENITO JUAREZ,Benito Juárez,CDMX,19.368983,-99.160125,31,29
4386,2024,7,2024-07-31,22:26:29,2024,7,2024-07-30,18:29:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,ARAGÓN INGUARÁN,Aragon Inguaran,GUSTAVO A. MADERO,Gustavo A. Madero,CDMX,19.472882,-99.107782,31,30
4387,2024,7,2024-07-31,22:43:38,2024,7,2024-07-31,20:37:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,MERCED BALBUENA,Merced Balbuena,VENUSTIANO CARRANZA,Venustiano Carranza,CDMX,19.418268,-99.123957,31,31
4388,2024,7,2024-07-31,23:15:08,2024,1,2024-01-05,10:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,SANTA ÚRSULA XITLA,Pueblo Santa Ursula Xitla,TLALPAN,Tlalpan,CDMX,19.283727,-99.175853,31,5
4389,2024,7,2024-07-31,23:55:36,2024,7,2024-07-31,10:00:00,USURPACIÓN DE IDENTIDAD,DELITO DE BAJO IMPACTO,...,FUERO COMUN,HÉROES DE CHURUBUSCO,Heroes De Churubusco,IZTAPALAPA,Iztapalapa,CDMX,19.362676,-99.121012,31,31